import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ShieldCheck, AlertTriangle, ChevronDown, ExternalLink } from 'lucide-react';

/**
 * Reusable card to render live backend compliance evaluation verdicts and reasoning.
 * Replacing old hardcoded/mock metrics and citations.
 *
 * @param {boolean} isCompliant - Verdict from FastAPI backend judge agent.
 * @param {string} reasoning - Detailed explanation of the policy evaluation.
 */
export const PlacementVerdictCard = ({ isCompliant, reasoning }) => {
  const [isOpen, setIsOpen] = useState(false);
  const isEligible = isCompliant === true;

  if (isCompliant === undefined || isCompliant === null) return null;

  return (
    <div className="border border-panelBorder bg-black/10 dark:bg-black/20 rounded-xl overflow-hidden transition-all shrink-0 w-full">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-3.5 hover:bg-white/[0.02] dark:hover:bg-white/[0.01] text-left transition-colors cursor-pointer gap-3"
      >
        <div className="flex items-center gap-2.5 min-w-0">
          {isEligible ? (
            <ShieldCheck size={16} className="text-green-400 shrink-0 shadow-sm" />
          ) : (
            <AlertTriangle size={16} className="text-red-400 shrink-0 shadow-sm animate-pulse" />
          )}
          <span className="font-bold text-textMain text-[13px] sm:text-[14px] truncate leading-tight flex items-center gap-2">
            Placement Verdict: 
            <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold border ${
              isEligible 
                ? 'bg-green-500/10 border-green-500/20 text-green-400' 
                : 'bg-red-500/10 border-red-500/20 text-red-400'
            }`}>
              {isEligible ? 'Compliant / Eligible' : 'Flagged exception / Review'}
            </span>
          </span>
        </div>
        <div className="flex items-center gap-2 text-textMuted shrink-0">
          <span className="text-[11px] font-medium text-primary hover:underline flex items-center gap-1">
            Details
          </span>
          <motion.div
            animate={{ rotate: isOpen ? 180 : 0 }}
            transition={{ duration: 0.2 }}
          >
            <ChevronDown size={14} />
          </motion.div>
        </div>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: "easeInOut" }}
          >
            <div className="px-4 pb-4 pt-1.5 flex flex-col gap-3 border-t border-panelBorder bg-black/[0.05] dark:bg-black/[0.15] text-[12px] leading-relaxed">
              <div className="flex flex-col gap-1.5 mt-1.5">
                <span className="text-[10px] font-bold text-secondary uppercase tracking-wider flex items-center gap-1">
                  <ExternalLink size={11} /> Agent reasoning & policy context
                </span>
                <div className="p-3 bg-white/[0.02] dark:bg-black/20 border border-panelBorder rounded-lg text-textMain font-light italic tracking-wide whitespace-pre-wrap">
                  {reasoning || "No detailed policy reasoning generated by the agent pipeline."}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
